CREATE TABLE user(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
    email VARCHAR(64) NULL DEFAULT '',
    nickName VARCHAR(64) NOT NULL DEFAULT '',
    password VARCHAR(255) NOT NULL DEFAULT '',
    status SMALLINT DEFAULT 0 ,
    role SMALLINT DEFAULT 0,
    integral INT DEFAULT 0 COMMENT '积分数',
    sid VARCHAR(255) DEFAULT '',
    headUrl VARCHAR(255) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_logined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '用户';

CREATE TABLE customer(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) DEFAULT '',
  idNum VARCHAR(32) DEFAULT '',
  cell VARCHAR(32)  DEFAULT '',
  bankId VARCHAR(32) DEFAULT '',
  linkManCell VARCHAR(32) DEFAULT '',
  homeAddress VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '被查人信息';

CREATE TABLE report(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) DEFAULT '',
  num VARCHAR(16)  DEFAULT '',
  userId INT UNSIGNED NOT NULL COMMENT '',
  customerId INT UNSIGNED NOT NULL COMMENT '',
  serviceList VARCHAR(64)  DEFAULT '',
  payout INT UNSIGNED DEFAULT 0 COMMENT '共消耗点数',
  status SMALLINT DEFAULT 1 ,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '报告';

CREATE TABLE goods(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) DEFAULT '',
  price INT UNSIGNED DEFAULT 0 COMMENT '售价',
  status SMALLINT DEFAULT 1 ,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '服务';

CREATE TABLE adminlog(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  adminId INT UNSIGNED NOT NULL COMMENT '操作人id',
  adminName VARCHAR(32) DEFAULT '',
  userId INT UNSIGNED NOT NULL COMMENT '被操作人id',
  userName VARCHAR(32) DEFAULT '',
  integral INT DEFAULT 0 COMMENT '积分',
  msg VARCHAR(256) DEFAULT '',
  status SMALLINT DEFAULT 1 COMMENT '1:新增用户;2:修改用户',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '管理员操作日志';

CREATE TABLE applyloan(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  als_d7_id_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_d7_id_bank_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_id_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_bank_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_d7_cell_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_d15_id_bank_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_id_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_bank_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_d15_cell_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m1_id_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_id_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m1_cell_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_max_inteday VARCHAR(6)  DEFAULT '',
  als_m3_id_min_inteday VARCHAR(6)  DEFAULT '',
  als_m3_id_tot_mons VARCHAR(6)  DEFAULT '',
  als_m3_id_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_max_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_min_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m3_id_bank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m3_id_nbank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m3_cell_max_inteday VARCHAR(6)  DEFAULT '',
  als_m3_cell_min_inteday VARCHAR(6)  DEFAULT '',
  als_m3_cell_tot_mons VARCHAR(6)  DEFAULT '',
  als_m3_cell_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_max_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_min_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m3_cell_bank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m3_cell_nbank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m6_id_max_inteday VARCHAR(6)  DEFAULT '',
  als_m6_id_min_inteday VARCHAR(6)  DEFAULT '',
  als_m6_id_tot_mons VARCHAR(6)  DEFAULT '',
  als_m6_id_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_max_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_min_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m6_id_bank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m6_id_nbank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m6_cell_max_inteday VARCHAR(6)  DEFAULT '',
  als_m6_cell_min_inteday VARCHAR(6)  DEFAULT '',
  als_m6_cell_tot_mons VARCHAR(6)  DEFAULT '',
  als_m6_cell_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_max_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_min_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m6_cell_bank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m6_cell_nbank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m12_id_max_inteday VARCHAR(6)  DEFAULT '',
  als_m12_id_min_inteday VARCHAR(6)  DEFAULT '',
  als_m12_id_tot_mons VARCHAR(6)  DEFAULT '',
  als_m12_id_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_max_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_min_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m12_id_bank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m12_id_nbank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m12_cell_max_inteday VARCHAR(6)  DEFAULT '',
  als_m12_cell_min_inteday VARCHAR(6)  DEFAULT '',
  als_m12_cell_tot_mons VARCHAR(6)  DEFAULT '',
  als_m12_cell_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_max_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_min_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_selfnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m12_cell_bank_min_inteday VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_selfnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_p2p_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_mc_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_ca_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_cf_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_com_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_oth_allnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_p2p_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_mc_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_ca_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_cf_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_com_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_oth_orgnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_tot_mons VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_avg_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_max_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_min_monnum VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_max_inteday VARCHAR(6)  DEFAULT '',
  als_m12_cell_nbank_min_inteday VARCHAR(6)  DEFAULT '',
  als_fst_id_bank_inteday VARCHAR(6)  DEFAULT '',
  als_fst_id_nbank_inteday VARCHAR(6)  DEFAULT '',
  als_fst_cell_bank_inteday VARCHAR(6)  DEFAULT '',
  als_fst_cell_nbank_inteday VARCHAR(6)  DEFAULT '',
  als_lst_id_bank_inteday VARCHAR(6)  DEFAULT '',
  als_lst_id_bank_consnum VARCHAR(6)  DEFAULT '',
  als_lst_id_bank_csinteday VARCHAR(6)  DEFAULT '',
  als_lst_id_nbank_inteday VARCHAR(6)  DEFAULT '',
  als_lst_id_nbank_consnum VARCHAR(6)  DEFAULT '',
  als_lst_id_nbank_csinteday VARCHAR(6)  DEFAULT '',
  als_lst_cell_bank_inteday VARCHAR(6)  DEFAULT '',
  als_lst_cell_bank_consnum VARCHAR(6)  DEFAULT '',
  als_lst_cell_bank_csinteday VARCHAR(6)  DEFAULT '',
  als_lst_cell_nbank_inteday VARCHAR(6)  DEFAULT '',
  als_lst_cell_nbank_consnum VARCHAR(6)  DEFAULT '',
  als_lst_cell_nbank_csinteday VARCHAR(6)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '借贷意向验证';

CREATE TABLE execution(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  ex_bad1_name VARCHAR(24)  DEFAULT '',
  ex_bad1_cid VARCHAR(24)  DEFAULT '',
  ex_bad1_cidtype VARCHAR(24)  DEFAULT '',
  ex_bad1_datatime VARCHAR(24)  DEFAULT '',
  ex_bad1_datatypeid VARCHAR(24)  DEFAULT '',
  ex_bad1_datatype VARCHAR(24)  DEFAULT '',
  ex_bad1_leader VARCHAR(24)  DEFAULT '',
  ex_bad1_address VARCHAR(24)  DEFAULT '',
  ex_bad1_court VARCHAR(24)  DEFAULT '',
  ex_bad1_time VARCHAR(24)  DEFAULT '',
  ex_bad1_casenum VARCHAR(24)  DEFAULT '',
  ex_bad1_money VARCHAR(24)  DEFAULT '',
  ex_bad1_base VARCHAR(24)  DEFAULT '',
  ex_bad1_basecompany VARCHAR(24)  DEFAULT '',
  ex_bad1_obligation VARCHAR(24)  DEFAULT '',
  ex_bad1_lasttime VARCHAR(24)  DEFAULT '',
  ex_bad1_performance VARCHAR(24)  DEFAULT '',
  ex_bad1_concretesituation VARCHAR(24)  DEFAULT '',
  ex_bad1_breaktime VARCHAR(24)  DEFAULT '',
  ex_bad1_posttime VARCHAR(24)  DEFAULT '',
  ex_bad1_performedpart VARCHAR(24)  DEFAULT '',
  ex_bad1_unperformpart VARCHAR(24)  DEFAULT '',
  ex_execut1_name VARCHAR(24)  DEFAULT '',
  ex_execut1_cid VARCHAR(24)  DEFAULT '',
  ex_execut1_cidtype VARCHAR(24)  DEFAULT '',
  ex_execut1_datatime VARCHAR(24)  DEFAULT '',
  ex_execut1_datatypeid VARCHAR(24)  DEFAULT '',
  ex_execut1_datatype VARCHAR(24)  DEFAULT '',
  ex_execut1_court VARCHAR(24)  DEFAULT '',
  ex_execut1_time VARCHAR(24)  DEFAULT '',
  ex_execut1_casenum VARCHAR(24)  DEFAULT '',
  ex_execut1_money VARCHAR(24)  DEFAULT '',
  ex_execut1_statute VARCHAR(24)  DEFAULT '',
  ex_execut1_basic VARCHAR(24)  DEFAULT '',
  ex_execut1_basiccourt VARCHAR(24)  DEFAULT '',
  ex_bad2_name VARCHAR(24)  DEFAULT '',
  ex_bad2_cid VARCHAR(24)  DEFAULT '',
  ex_bad2_cidtype VARCHAR(24)  DEFAULT '',
  ex_bad2_datatime VARCHAR(24)  DEFAULT '',
  ex_bad2_datatypeid VARCHAR(24)  DEFAULT '',
  ex_bad2_datatype VARCHAR(24)  DEFAULT '',
  ex_bad2_leader VARCHAR(24)  DEFAULT '',
  ex_bad2_address VARCHAR(24)  DEFAULT '',
  ex_bad2_court VARCHAR(24)  DEFAULT '',
  ex_bad2_time VARCHAR(24)  DEFAULT '',
  ex_bad2_casenum VARCHAR(24)  DEFAULT '',
  ex_bad2_money VARCHAR(24)  DEFAULT '',
  ex_bad2_base VARCHAR(24)  DEFAULT '',
  ex_bad2_basecompany VARCHAR(24)  DEFAULT '',
  ex_bad2_obligation VARCHAR(24)  DEFAULT '',
  ex_bad2_lasttime VARCHAR(24)  DEFAULT '',
  ex_bad2_performance VARCHAR(24)  DEFAULT '',
  ex_bad2_concretesituation VARCHAR(24)  DEFAULT '',
  ex_bad2_breaktime VARCHAR(24)  DEFAULT '',
  ex_bad2_posttime VARCHAR(24)  DEFAULT '',
  ex_bad2_performedpart VARCHAR(24)  DEFAULT '',
  ex_bad2_unperformpart VARCHAR(24)  DEFAULT '',
  ex_execut2_name VARCHAR(24)  DEFAULT '',
  ex_execut2_cid VARCHAR(24)  DEFAULT '',
  ex_execut2_cidtype VARCHAR(24)  DEFAULT '',
  ex_execut2_datatime VARCHAR(24)  DEFAULT '',
  ex_execut2_datatypeid VARCHAR(24)  DEFAULT '',
  ex_execut2_datatype VARCHAR(24)  DEFAULT '',
  ex_execut2_court VARCHAR(24)  DEFAULT '',
  ex_execut2_time VARCHAR(24)  DEFAULT '',
  ex_execut2_casenum VARCHAR(24)  DEFAULT '',
  ex_execut2_money VARCHAR(24)  DEFAULT '',
  ex_execut2_statute VARCHAR(24)  DEFAULT '',
  ex_execut2_basic VARCHAR(24)  DEFAULT '',
  ex_execut2_basiccourt VARCHAR(24)  DEFAULT '',
  ex_execut3_name VARCHAR(24)  DEFAULT '',
  ex_execut3_cid VARCHAR(24)  DEFAULT '',
  ex_execut3_cidtype VARCHAR(24)  DEFAULT '',
  ex_execut3_datatime VARCHAR(24)  DEFAULT '',
  ex_execut3_datatypeid VARCHAR(24)  DEFAULT '',
  ex_execut3_datatype VARCHAR(24)  DEFAULT '',
  ex_execut3_court VARCHAR(24)  DEFAULT '',
  ex_execut3_time VARCHAR(24)  DEFAULT '',
  ex_execut3_casenum VARCHAR(24)  DEFAULT '',
  ex_execut3_money VARCHAR(24)  DEFAULT '',
  ex_execut3_statute VARCHAR(24)  DEFAULT '',
  ex_execut3_basic VARCHAR(24)  DEFAULT '',
  ex_execut3_basiccourt VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '法院被执行人';

CREATE TABLE inforelation(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  ir_id_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_id_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_cell_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_id_inlistwith_cell VARCHAR(10)  DEFAULT '',
  ir_cell_inlistwith_id VARCHAR(10)  DEFAULT '',
  ir_allmatch_days VARCHAR(10)  DEFAULT '',
  ir_id_x_cell_notmat_days VARCHAR(36)  DEFAULT '',
  ir_cell_x_id_notmat_days VARCHAR(36)  DEFAULT '',
  ir_id_x_cell_lastchg_days VARCHAR(10)  DEFAULT '',
  ir_cell_x_id_lastchg_days VARCHAR(10)  DEFAULT '',
  ir_id_is_reabnormal VARCHAR(10)  DEFAULT '',
  ir_cell_is_reabnormal VARCHAR(10)  DEFAULT '',
  ir_mail_is_reabnormal VARCHAR(10)  DEFAULT '',
  ir_m1_id_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_id_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_cell_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_id_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_id_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_id_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_cell_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_cell_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_linkman_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_linkman_cell_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_linkman_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_tel_home_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_tel_home_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_home_addr_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_home_addr_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_tel_home_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m1_home_addr_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_id_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_id_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_cell_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_id_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_id_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_id_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_cell_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_cell_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_linkman_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_linkman_cell_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_linkman_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_tel_home_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_tel_home_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_home_addr_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_home_addr_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_tel_home_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m3_home_addr_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_id_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_id_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_cell_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_id_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_id_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_id_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_cell_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_cell_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_linkman_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_linkman_cell_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_linkman_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_tel_home_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_tel_home_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_home_addr_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_home_addr_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_tel_home_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m6_home_addr_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_id_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_id_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_cell_x_mail_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_id_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_id_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_id_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_cell_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_cell_x_biz_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_linkman_cell_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_linkman_cell_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_linkman_cell_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_tel_home_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_tel_home_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_home_addr_x_cell_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_home_addr_x_id_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_tel_home_x_home_addr_cnt VARCHAR(10)  DEFAULT '',
  ir_m12_home_addr_x_tel_home_cnt VARCHAR(10)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '实名信息验证';

CREATE TABLE riskstrategy(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,

  rs_final_decision VARCHAR(12)  DEFAULT '',
  rs_strategy_id VARCHAR(12)  DEFAULT '',
  rs_strategy_version VARCHAR(12)  DEFAULT '',
  rs_platform VARCHAR(12)  DEFAULT '',
  rs_scene VARCHAR(12)  DEFAULT '',
  rs_product_name VARCHAR(12)  DEFAULT '',
  rs_product_type VARCHAR(12)  DEFAULT '',
  rs_Rule_weight VARCHAR(12)  DEFAULT '',
  rs_Rule_decision VARCHAR(12)  DEFAULT '',
  rs_ScoreAf_scoreafcust VARCHAR(12)  DEFAULT '',
  rs_ScoreAf_decision VARCHAR(12)  DEFAULT '',
  rs_Score_scorebankv2 VARCHAR(12)  DEFAULT '',
  rs_Socre_decision VARCHAR(12)  DEFAULT '',
  Rule_final_weight VARCHAR(12)  DEFAULT '',
  Rule_final_decision VARCHAR(12)  DEFAULT '',
  rule_weight_QJE010 VARCHAR(12)  DEFAULT '',
  rule_weight_QJE020 VARCHAR(12)  DEFAULT '',
  rule_weight_QJE040 VARCHAR(12)  DEFAULT '',
  rule_weight_QJE050 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD010 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD020 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD030 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD040 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD050 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD060 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD070 VARCHAR(12)  DEFAULT '',
  rule_weight_QCD080 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS150 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS151 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS152 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS153 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS154 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS155 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS156 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS157 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS158 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS159 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS160 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS161 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS162 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS163 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS164 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS165 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS166 VARCHAR(12)  DEFAULT '',
  rule_weight_QJS167 VARCHAR(12)  DEFAULT '',
  rule_weight_CBC001 VARCHAR(12)  DEFAULT '',
  rule_weight_CBC002 VARCHAR(12)  DEFAULT '',
  rule_weight_CBC003 VARCHAR(12)  DEFAULT '',
  rule_weight_CBC004 VARCHAR(12)  DEFAULT '',
  rule_weight_CAC001 VARCHAR(12)  DEFAULT '',
  rule_weight_CAC002 VARCHAR(12)  DEFAULT '',
  rule_weight_CAC003 VARCHAR(12)  DEFAULT '',
  rule_weight_CAC004 VARCHAR(12)  DEFAULT '',
  Rule_name_QJE010 VARCHAR(12)  DEFAULT '',
  Rule_name_QJE020 VARCHAR(12)  DEFAULT '',
  Rule_name_QJE040 VARCHAR(12)  DEFAULT '',
  Rule_name_QJE050 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD010 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD020 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD030 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD040 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD050 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD060 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD070 VARCHAR(12)  DEFAULT '',
  Rule_name_QCD080 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS150 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS151 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS152 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS153 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS154 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS155 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS156 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS157 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS158 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS159 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS160 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS161 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS162 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS163 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS164 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS165 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS166 VARCHAR(12)  DEFAULT '',
  Rule_name_QJS167 VARCHAR(12)  DEFAULT '',
  Rule_name_CBC001 VARCHAR(12)  DEFAULT '',
  Rule_name_CBC002 VARCHAR(12)  DEFAULT '',
  Rule_name_CBC003 VARCHAR(12)  DEFAULT '',
  Rule_name_CBC004 VARCHAR(12)  DEFAULT '',
  Rule_name_CAC001 VARCHAR(12)  DEFAULT '',
  Rule_name_CAC002 VARCHAR(12)  DEFAULT '',
  Rule_name_CAC003 VARCHAR(12)  DEFAULT '',
  Rule_name_CAC004 VARCHAR(12)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '策略引擎';

CREATE TABLE speciallist(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,

  sl_id_abnormal VARCHAR(6)  DEFAULT '',
  sl_id_phone_overdue VARCHAR(6)  DEFAULT '',
  sl_id_court_bad VARCHAR(6)  DEFAULT '',
  sl_id_court_executed VARCHAR(6)  DEFAULT '',
  sl_id_bank_bad VARCHAR(6)  DEFAULT '',
  sl_id_bank_overdue VARCHAR(6)  DEFAULT '',
  sl_id_bank_fraud VARCHAR(6)  DEFAULT '',
  sl_id_bank_lost VARCHAR(6)  DEFAULT '',
  sl_id_bank_refuse VARCHAR(6)  DEFAULT '',
  sl_id_p2p_bad VARCHAR(6)  DEFAULT '',
  sl_id_p2p_overdue VARCHAR(6)  DEFAULT '',
  sl_id_p2p_fraud VARCHAR(6)  DEFAULT '',
  sl_id_p2p_lost VARCHAR(6)  DEFAULT '',
  sl_id_p2p_refuse VARCHAR(6)  DEFAULT '',
  sl_id_nbank_p2p_bad VARCHAR(6)  DEFAULT '',
  sl_id_nbank_p2p_overdue VARCHAR(6)  DEFAULT '',
  sl_id_nbank_p2p_fraud VARCHAR(6)  DEFAULT '',
  sl_id_nbank_p2p_lost VARCHAR(6)  DEFAULT '',
  sl_id_nbank_p2p_refuse VARCHAR(6)  DEFAULT '',
  sl_id_nbank_mc_bad VARCHAR(6)  DEFAULT '',
  sl_id_nbank_mc_overdue VARCHAR(6)  DEFAULT '',
  sl_id_nbank_mc_fraud VARCHAR(6)  DEFAULT '',
  sl_id_nbank_mc_lost VARCHAR(6)  DEFAULT '',
  sl_id_nbank_mc_refuse VARCHAR(6)  DEFAULT '',
  sl_id_nbank_ca_bad VARCHAR(6)  DEFAULT '',
  sl_id_nbank_ca_overdue VARCHAR(6)  DEFAULT '',
  sl_id_nbank_ca_fraud VARCHAR(6)  DEFAULT '',
  sl_id_nbank_ca_lost VARCHAR(6)  DEFAULT '',
  sl_id_nbank_ca_refuse VARCHAR(6)  DEFAULT '',
  sl_id_nbank_com_bad VARCHAR(6)  DEFAULT '',
  sl_id_nbank_com_overdue VARCHAR(6)  DEFAULT '',
  sl_id_nbank_com_fraud VARCHAR(6)  DEFAULT '',
  sl_id_nbank_com_lost VARCHAR(6)  DEFAULT '',
  sl_id_nbank_com_refuse VARCHAR(6)  DEFAULT '',
  sl_id_nbank_cf_bad VARCHAR(6)  DEFAULT '',
  sl_id_nbank_cf_overdue VARCHAR(6)  DEFAULT '',
  sl_id_nbank_cf_fraud VARCHAR(6)  DEFAULT '',
  sl_id_nbank_cf_lost VARCHAR(6)  DEFAULT '',
  sl_id_nbank_cf_refuse VARCHAR(6)  DEFAULT '',
  sl_id_nbank_other_bad VARCHAR(6)  DEFAULT '',
  sl_id_nbank_other_overdue VARCHAR(6)  DEFAULT '',
  sl_id_nbank_other_fraud VARCHAR(6)  DEFAULT '',
  sl_id_nbank_other_lost VARCHAR(6)  DEFAULT '',
  sl_id_nbank_other_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_abnormal VARCHAR(6)  DEFAULT '',
  sl_cell_phone_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_bank_bad VARCHAR(6)  DEFAULT '',
  sl_cell_bank_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_bank_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_bank_lost VARCHAR(6)  DEFAULT '',
  sl_cell_bank_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_p2p_bad VARCHAR(6)  DEFAULT '',
  sl_cell_p2p_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_p2p_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_p2p_lost VARCHAR(6)  DEFAULT '',
  sl_cell_p2p_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_p2p_bad VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_p2p_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_p2p_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_p2p_lost VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_p2p_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_mc_bad VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_mc_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_mc_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_mc_lost VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_mc_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_ca_bad VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_ca_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_ca_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_ca_lost VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_ca_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_com_bad VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_com_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_com_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_com_lost VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_com_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_cf_bad VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_cf_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_cf_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_cf_lost VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_cf_refuse VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_other_bad VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_other_overdue VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_other_fraud VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_other_lost VARCHAR(6)  DEFAULT '',
  sl_cell_nbank_other_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_abnormal VARCHAR(6)  DEFAULT '',
  sl_lm_cell_phone_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_bank_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_bank_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_bank_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_bank_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_bank_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_p2p_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_p2p_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_p2p_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_p2p_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_p2p_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_mc_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_mc_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_mc_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_mc_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_mc_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_ca_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_ca_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_ca_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_ca_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_ca_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_com_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_com_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_com_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_com_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_com_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_cf_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_cf_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_cf_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_cf_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_cf_refuse VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_other_bad VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_other_overdue VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_other_fraud VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_other_lost VARCHAR(6)  DEFAULT '',
  sl_lm_cell_nbank_other_refuse  VARCHAR(6)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '特殊名单';

CREATE TABLE bankfourpro(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  result VARCHAR(12)  DEFAULT '',
  msg VARCHAR(128)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '银行卡四要素';

CREATE TABLE telchecks(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  operation VARCHAR(24)  DEFAULT '',
  result VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '手机三要素简版';

CREATE TABLE telperiod(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  operation VARCHAR(24)  DEFAULT '',
  result VARCHAR(24)  DEFAULT '',
  value VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '手机在网时长';

CREATE TABLE telstatus(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  operation VARCHAR(24)  DEFAULT '',
  result VARCHAR(24)  DEFAULT '',
  value VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '手机在网状态';

CREATE TABLE bankcard(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  message VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '阿里银行卡三要素';

CREATE TABLE blackname(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  msg VARCHAR(24) DEFAULT '',
  orderNo VARCHAR(36) DEFAULT '',
  blackType1 VARCHAR(24)  DEFAULT '',
  blackCount1 VARCHAR(24)  DEFAULT '',
  blackType2 VARCHAR(24)  DEFAULT '',
  blackCount2 VARCHAR(24)  DEFAULT '',
  blackType3 VARCHAR(24)  DEFAULT '',
  blackCount3 VARCHAR(24)  DEFAULT '',
  blackType4 VARCHAR(24)  DEFAULT '',
  blackCount4 VARCHAR(24)  DEFAULT '',
  blackType5 VARCHAR(24)  DEFAULT '',
  blackCount5 VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '阿里个人黑名单多头借贷综合查询';

CREATE TABLE blacknamelist(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  blackNameId INT UNSIGNED NOT NULL COMMENT '',
  blackRiskType VARCHAR(24)  DEFAULT '',
  blackFactsType VARCHAR(24)  DEFAULT '',
  blackFacts VARCHAR(512)  DEFAULT '',
  blackHappenDate VARCHAR(24)  DEFAULT '',
  blackAmt VARCHAR(24) DEFAULT '金额',
  blackPublishSource VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '阿里黑名单中的list数据';

CREATE TABLE cell(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  code VARCHAR(24)  DEFAULT '',
  prov VARCHAR(24)  DEFAULT '',
  name VARCHAR(24)  DEFAULT '',
  city VARCHAR(24)  DEFAULT '',
  msg VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '阿里手机归属地';

CREATE TABLE cellcheck(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  code VARCHAR(24)  DEFAULT '',
  msg VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '阿里手机验证';

CREATE TABLE idcard(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  idCardPhoto LONGTEXT NOT NULL COMMENT '',
  message VARCHAR(24)  DEFAULT '',
  area VARCHAR(24)  DEFAULT '',
  birthday VARCHAR(24)  DEFAULT '',
  sex VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '阿里身份证实名认证返回照片';

CREATE TABLE badrecord(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  code VARCHAR(24)  DEFAULT '',
  code2 VARCHAR(24)  DEFAULT '',
  msg VARCHAR(24)  DEFAULT '',
  message VARCHAR(24)  DEFAULT '',
  name VARCHAR(24)  DEFAULT '',
  idcard VARCHAR(24)  DEFAULT '',
  case_time VARCHAR(24)  DEFAULT '',
  description VARCHAR(128)  DEFAULT '',
  res VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '狗东不良行为记录查询';

CREATE TABLE celllong(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  code VARCHAR(24)  DEFAULT '',
  charge VARCHAR(24)  DEFAULT '',
  msg VARCHAR(24)  DEFAULT '',
  mobile VARCHAR(24)  DEFAULT '',
  description VARCHAR(24)  DEFAULT '',
  message VARCHAR(24)  DEFAULT '',
  idcard VARCHAR(24)  DEFAULT '',
  name VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '京东手机在线时长';

CREATE TABLE carshield(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  reportId INT UNSIGNED NOT NULL COMMENT '',
  flag SMALLINT DEFAULT 0 ,
  code VARCHAR(24)  DEFAULT '',
  code2 VARCHAR(24)  DEFAULT '',
  charge VARCHAR(24)  DEFAULT '',
  msg VARCHAR(24)  DEFAULT '',
  count VARCHAR(24)  DEFAULT '',
  value VARCHAR(128)  DEFAULT '',
  message VARCHAR(24)  DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '京东多维度租车黑名单';

CREATE TABLE selfblackname(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(24)  DEFAULT '',
  idNum VARCHAR(24)  DEFAULT '',
  cell VARCHAR(24)  DEFAULT '',
  reason VARCHAR(128)  DEFAULT '原因',
  degree VARCHAR(24) DEFAULT '程度',
  company VARCHAR(24) DEFAULT '公司',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET =utf8 COMMENT = '自建黑名单';